project:
  type: website

website:
  title: "Vanda Suklar"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Academic Background

  page-footer:
    right: "&copy; 2024, Vanda Suklar" 
  
        
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute: 
  freeze: auto 

